DROP TABLE IF EXISTS Profiles;
DROP TABLE IF EXISTS Profiles_History;
DROP TABLE IF EXISTS Config;
DROP TABLE IF EXISTS Stock_Orders;
DROP TABLE IF EXISTS Stock_Simulations;
DROP TABLE IF EXISTS Stock_Orders_History;