DROP TABLE IF EXISTS Stock_Orders;
DROP TABLE IF EXISTS Stock_Simulations;
DROP TABLE IF EXISTS Stock_Holdings;
DROP TABLE IF EXISTS Stock_Records;
DROP TABLE IF EXISTS Stock_Config;
DROP TABLE IF EXISTS Profiles;
DROP TABLE IF EXISTS Config;